import pygame

#building
NUM_OF_FLOORS = 30
NUM_OF_ELEVATORS = 3

# sizes
FLOOR_HEIGHT = 80
FLOOR_WIDTH = 200

ELEVATOR_HEIGHT = 80
ELEVATOR_WIDTH = 80

FLOOR_IMAGE_PATH = 'resources/floor.jpeg'
ELEVATOR_IMAGE_PATH = 'resources/elv.png'
DING_SOUND_PATH = 'resources/ding.mp3'

FONT_SIZE = 25

WINDOW_HEIGHT = 1000
WINDOW_WIDTH = 600


SCROLL_SPEED = 20
BUTTON_RADIUS = 16

FLOOR_SPACER_HEIGHT = 7
MARGIN = 8
ELEVATOR_SPACER = 8
ELEVATOR_START_X = MARGIN + FLOOR_WIDTH + ELEVATOR_SPACER

# colors
WHITE = 255, 255, 255
BLACK = 0, 0, 0
BUTTON_COLOR = LIGHT_GREY = 200, 200, 200
GREEN = 60, 179, 113

# times
ELEVATOR_STOPPING_TIME_AT_FLOOR = 2000 # ms
ELEVATOR_TRAVEL_TIME_PER_FLOOR = 0.5 # seconds
PIXELS_PER_SECOND = int(FLOOR_HEIGHT / ELEVATOR_TRAVEL_TIME_PER_FLOOR)

# mouse buttons
LEFT = 1
MOUSE_WHEEL_UP = 4
MOUSE_WHEEL_DOWN = 5